apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sampe-ipblock-ingress-networkpolicy
  namespace: nptest
spec:
  podSelector:
    matchLabels:
      app: np4
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 10.8.1.16/32
      ports:
        - protocol: TCP
          port: 80
