apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap
data:
  thread: "6"
  connection.max: "100"
  connection.min: "10"
  sample.properties: 1
    property.1=value1
    property.2=value2
    property.3=value3
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;
  test.sh: |-
    #!/bin/bash
    echo "Hello, kubernetes"
    sleep infinity
